SELECT * FROM EMP;

SELECT INITCAP(ENAME) FROM EMP;

SELECT ENAME, SUBSTR(ENAME,2,3) FROM EMP;

SELECT LENGTH(ENAME) FROM EMP;

SELECT LOWER(SUBSTR(ENAME,1,1)),LOWER(SUBSTR(ENAME,-1)) FROM EMP;

SELECT ROUND(3456.78,1) AS ROUND_1 FROM DUAL;

SELECT TO_CHAR(TRUNC(SAL*50,-2),'999,999,999')||'원' AS "계산결과" FROM EMP;

SELECT ENAME,NVL2(TO_CHAR(COMM),'설정','미정') FROM EMP;

SELECT ENAME, EMPNO,DECODE(DEPTNO,'10','A부서','20','B부서','30','C부서','없당') FROM EMP;

SELECT ENAME, SAL  FROM EMP WHERE JOB='SALESMAN' AND SAL>=1000;

--job 대소문자 모를때 upper(job=...)하면서 대문자로 출력
SELECT SYSDATE "오늘날짜", SYSDATE+10 FROM DUAL;
--sysdate =가변
SELECT TO_CHAR(SYSDATE,'YYYY"년"fmmM"월"fmDD"일" fmHH12"시"fmMI"분"') FROM DUAL;
fm붙이면 fmmm.fmdd 경우 05월이 5월 됨

SELECT ENAME "이름",SAL "월급여",SAL*12+200*12 "연봉" FROM EMP;

SELECT ENAME "이름",SAL "월급", CASE  WHEN SAL<1000 THEN 'A' WHEN SAL<2000 THEN 'B' WHEN SAL<3000 THEN 'C'WHEN SAL<4000 THEN 'D' ELSE 'E' END "코드" FROM EMP;

SELECT ENAME "이름",DEPTNO "부서번호",DECODE(DEPTNO,10,'A',20,'B',30,'C',40,'E','F') AS "코드" FROM EMP;
SELECT ENAME FROM EMP WHERE ENAME LIKE '_A%';

SELECT CONCAT(ENAME, CONCAT(',',JOB)) AS "EMPLOYEE AND JOB TITLE" FROM EMP;

SELECT ENAME "이름" ,TO_CHAR(HIREDATE,'YYYY"년"MM"월"DD"일"') AS "입사일", TO_CHAR(HIREDATE,'DAY') AS "입사요일" FROM EMP ORDER BY TO_CHAR(HIREDATE-1,'DAY');

SELECT ENAME,ROUND(MONTHS_BETWEEN(SYSDATE,HIREDATE)) AS MONTHS_WORKED  FROM EMP ORDER BY MONTHS_WORKED;

SELECT ENAME "사원이름" ,TRUNC(SYSDATE-HIREDATE)||'일' "근무일수" FROM EMP;
SELECT ENAME,JOB,HIREDATE FROM EMP WHERE TO_CHAR(HIREDATE,'YYYY')=1981 ORDER BY HIREDATE;


SELECT ENAME,SAL,nvl(to_char(comm),'미정')FROM EMP; 
